# Generated by Django 5.0.6 on 2024-06-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_promotion_rename_author_book_authors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='unit_price',
        ),
    ]
