# Generated by Django 5.0.6 on 2024-07-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=555555, max_length=10),
            preserve_default=False,
        ),
    ]
