# Generated by Django 5.0.6 on 2024-07-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_address_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured_book',
        ),
    ]
