# Generated by Django 5.0.6 on 2024-07-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_category_featured_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='promotions',
            field=models.ManyToManyField(blank=True, null=True, to='core.promotion'),
        ),
    ]
