# Generated by Django 5.0.6 on 2024-07-11 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_book_description_alter_book_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='core.promotion'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
