# Generated by Django 5.0.6 on 2024-07-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cartitem_cart_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='static/images/KK_logo.jpeg', upload_to='thumbnail'),
        ),
    ]
