# Generated by Django 5.0.6 on 2024-07-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_total_cost_alter_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='promotions',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='static/images/KK_logo.jpeg', upload_to='static/images/thumbnail'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cart'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
