# Generated by Django 5.0.6 on 2024-07-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_book_promotions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
