# Generated by Django 5.0.6 on 2024-07-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_customer_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='static/images/KK_logo.jpeg', upload_to=''),
        ),
    ]
