# Generated by Django 5.0.6 on 2024-07-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_book_thumbnail_alter_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='membership',
        ),
    ]
