# Generated by Django 5.0.6 on 2024-07-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('C', 'Zaplaceno'), ('P', 'Čeká na zaplacení'), ('F', 'Platba selhala')], max_length=1),
        ),
    ]
